### ISSUE TITLE
Improve abort message

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/modelstats#2]
It would be nice to have a better abort message for `rs2 -cr` for when there are no current runs, than:
`Global .Rprofile loaded!`
`Error in myruns[[i]] : subscript out of bounds`
`Calls: <Anonymous> -> grepl`
`Execution halted`

**Comment by giannou** [comment]
Thanks for the feedback! Solved at https://github.com/pik-piam/modelstats/commit/ac11afb0f8333a66a05faf9d50957474766c4a16
