### ISSUE TITLE
modeltests() reports runs as both "Normal completion" and "did not start at all"

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/modelstats#84]
https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/blob/e564ac117ee64797f640fd992e7b5b341d8611de/README.md?blame=1#L22-23
and
https://gitlab.pik-potsdam.de/REMIND/testing_suite/-/blob/e564ac117ee64797f640fd992e7b5b341d8611de/README.md?blame=1#L50-52

**Comment by orichters** [comment]
I haven't really worked on how the script identifies the runs that were started. So maybe David is the one to have a look here?

**Comment by dklein-pik** [comment]
I'll look into it.
